/**
 * Workflow Exporter
 * Epic 10: Story 10.2
 *
 * Export workflows in various formats
 */

import { saveAs } from 'file-saver';

/**
 * Export workflow as pretty JSON
 */
export const exportAsJSON = (workflow) => {
  return JSON.stringify(workflow, null, 2);
};

/**
 * Download workflow as JSON file
 */
export const downloadAsJSON = (workflow, filename) => {
  const json = exportAsJSON(workflow);
  const blob = new Blob([json], { type: 'application/json' });
  const name = filename || `${workflow.name.replace(/\s+/g, '_')}_${Date.now()}.json`;
  saveAs(blob, name);
};

/**
 * Copy workflow JSON to clipboard
 */
export const copyToClipboard = async (workflow) => {
  const json = exportAsJSON(workflow);

  try {
    await navigator.clipboard.writeText(json);
    return { success: true };
  } catch (error) {
    return { success: false, error: error.message };
  }
};

/**
 * Export as GHL recreation steps (text)
 */
export const exportAsGHLSteps = (workflow) => {
  let steps = `WORKFLOW: ${workflow.name}\n`;
  steps += `${'='.repeat(workflow.name.length + 11)}\n\n`;

  if (workflow.description) {
    steps += `Description: ${workflow.description}\n\n`;
  }

  steps += `Nodes: ${workflow.nodes?.length || 0}\n`;
  steps += `Connections: ${workflow.connections?.length || 0}\n`;
  steps += `Difficulty: ${workflow.difficulty || 'beginner'}\n\n`;

  steps += `RECREATION STEPS:\n`;
  steps += `${'='.repeat(17)}\n\n`;

  if (workflow.nodes) {
    workflow.nodes.forEach((node, index) => {
      steps += `Step ${index + 1}: ${node.title}\n`;
      steps += `-`.repeat(40) + `\n`;
      steps += `Type: ${node.type}\n`;

      if (node.description) {
        steps += `Description: ${node.description}\n`;
      }

      if (node.params && Object.keys(node.params).length > 0) {
        steps += `Parameters:\n`;
        Object.entries(node.params).forEach(([key, value]) => {
          steps += `  - ${key}: ${value}\n`;
        });
      }

      steps += `\n`;
    });
  }

  if (workflow.connections && workflow.connections.length > 0) {
    steps += `CONNECTIONS:\n`;
    steps += `${'='.repeat(12)}\n\n`;

    workflow.connections.forEach((conn, index) => {
      const fromNode = workflow.nodes.find(n => n.id === conn.from);
      const toNode = workflow.nodes.find(n => n.id === conn.to);

      steps += `${index + 1}. ${fromNode?.title || conn.from} → ${toNode?.title || conn.to}`;
      if (conn.label) {
        steps += ` (${conn.label})`;
      }
      steps += `\n`;
    });
  }

  return steps;
};

/**
 * Download as text file
 */
export const downloadAsText = (workflow, filename) => {
  const text = exportAsGHLSteps(workflow);
  const blob = new Blob([text], { type: 'text/plain' });
  const name = filename || `${workflow.name.replace(/\s+/g, '_')}_steps_${Date.now()}.txt`;
  saveAs(blob, name);
};

/**
 * Generate deployment guide
 */
export const generateDeploymentGuide = (workflow) => {
  let guide = `# ${workflow.name} - Deployment Guide\n\n`;

  guide += `## Overview\n`;
  guide += `- **Difficulty**: ${workflow.difficulty || 'beginner'}\n`;
  guide += `- **Nodes**: ${workflow.nodes?.length || 0}\n`;
  guide += `- **Estimated Time**: ${estimateDeploymentTime(workflow)} minutes\n\n`;

  if (workflow.description) {
    guide += `## Description\n${workflow.description}\n\n`;
  }

  guide += `## Prerequisites\n`;
  guide += `- GoHighLevel account with workflow access\n`;
  guide += `- Required integrations set up\n`;
  guide += `- Contact data ready for testing\n\n`;

  guide += `## Step-by-Step Recreation\n\n`;

  if (workflow.nodes) {
    workflow.nodes.forEach((node, index) => {
      guide += `### Step ${index + 1}: ${node.title}\n\n`;
      guide += `**Type**: ${node.type}\n\n`;

      if (node.description) {
        guide += `**Description**: ${node.description}\n\n`;
      }

      guide += `**Configuration**:\n`;
      if (node.params && Object.keys(node.params).length > 0) {
        Object.entries(node.params).forEach(([key, value]) => {
          guide += `- ${key.replace(/_/g, ' ')}: \`${value}\`\n`;
        });
      } else {
        guide += `- Default settings\n`;
      }

      guide += `\n`;
    });
  }

  guide += `## Testing\n`;
  guide += `1. Create a test contact\n`;
  guide += `2. Trigger the workflow\n`;
  guide += `3. Verify each step executes correctly\n`;
  guide += `4. Check timing and conditions\n\n`;

  guide += `## Troubleshooting\n`;
  guide += `- Ensure all integrations are active\n`;
  guide += `- Check contact data has required fields\n`;
  guide += `- Verify trigger conditions\n`;
  guide += `- Review workflow logs in GHL\n\n`;

  guide += `---\n`;
  guide += `*Generated by BroBro*\n`;

  return guide;
};

/**
 * Estimate deployment time based on complexity
 */
const estimateDeploymentTime = (workflow) => {
  const nodeCount = workflow.nodes?.length || 0;
  const baseTime = 5; // 5 minutes base
  const perNode = 3; // 3 minutes per node
  return baseTime + nodeCount * perNode;
};
